# Generated by Django 5.1.2 on 2024-11-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='masters', to='salon.service'),
        ),
    ]
