# Generated by Django 5.1.2 on 2024-11-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_service_category_alter_service_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='masters', to='salon.service'),
        ),
    ]
