# Generated by Django 5.1.2 on 2024-11-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_master_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(),
        ),
    ]
